### ISSUE TITLE
rlp 3.0 removes bn.js in favor of native BigInt

### ISSUE THREAD

**Issue by srghma** [f-o-a-m/purescript-eth-core#25]
https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/rlp%403.0.0

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

https://caniuse.com/bigint

https://github.com/purescript/purescript/issues/3848

----

there is an error

```
Error: toBytes: received unsupported type object
    at toBytes (/home/srghma/projects/purescript-eth-core/node_modules/rlp/dist/index.js:249:11)
    at encode (/home/srghma/projects/purescript-eth-core/node_modules/rlp/dist/index.js:21:22)
    at Object.encode [as _rlpEncode] (/home/srghma/projects/purescript-eth-core/node_modules/rlp/dist/index.js:16:25)
    at rlpEncode (/home/srghma/projects/purescript-eth-core/output/Network.Ethereum.Core.RLP/index.js:116:38)
    at /home/srghma/projects/purescript-eth-core/output/Common/index.js:63:94
    at /home/srghma/projects/purescript-eth-core/output/CoreSpec.Signatures/index.js:43:156
    at /home/srghma/projects/purescript-eth-core/output/CoreSpec.Signatures/index.js:60:7
    at /home/srghma/projects/purescript-eth-core/output/Control.Monad.Writer.Trans/index.js:87:34
    at /home/srghma/projects/purescript-eth-core/output/Data.Identity/index.js:112:20
    at /home/srghma/projects/purescript-eth-core/output/Control.Monad.Writer.Trans/index.js:86:66
[error] Tests failed: exit code: 1
```

caused by this line 

https://github.com/ethereumjs/ethereumjs-monorepo/blob/aa7d323a1bddc5e1250c6861402c733037f32fa2/packages/rlp/src/index.ts#L274

the type of `<BN: 29>` is `object`

----------

We could use:
1. native BigInt, with latest node
2. https://github.com/sharkdp/purescript-bigints with polyfill https://github.com/peterolson/BigInteger.js

**Comment by srghma** [comment]
also 

```
exports._rlpEncode = rlp.encode;
```

should be changed to

```
exports._rlpEncode = rlpval => Buffer.from(rlp.encode(rlpval));
```

or return https://github.com/purescript-contrib/purescript-arraybuffer-types/blob/505aa3de50a1400e5f2fce4a8e7b1a39abaa8fd9/src/Data/ArrayBuffer/Types.purs#L33 instead of bytestring
